### ISSUE TITLE
Quasar framework support

### ISSUE THREAD

**Issue by Akryum** [histoire-dev/histoire#105]
https://twitter.com/dakoba/status/1532629503138226177

**Comment by IlCallo** [comment]
Check out this helper we created to extract Quasar config (both for webpack-based and Vite-based CLI): https://github.com/quasarframework/quasar-testing/blob/dev/packages/e2e-cypress/src/helpers/cct-dev-server/index.ts

Let me know if you need further guidance

**Comment by HoaiLee** [comment]
@IlCallo Is this possible to integrate Histoire with Quasar now?

**Comment by Paracelsus-Rose** [comment]
> Check out this helper we created to extract Quasar config (both for webpack-based and Vite-based CLI): https://github.com/quasarframework/quasar-testing/blob/dev/packages/e2e-cypress/src/helpers/cct-dev-server/index.ts
> 
> Let me know if you need further guidance

Not sure exactly how to use this supplied helper to get histoire/quasar working together.  Appreciate any insights :-)

**Comment by IlCallo** [comment]
As far as I can tell, you just need to copy over the config extractor helper in your project, then return it from your [histoire or Vite configuration](https://histoire.dev/guide/config.html), if Historie/Vite support an async config to be returned

**Comment by Paracelsus-Rose** [comment]
Tried for a few hours to get it working, was unable to reproduce a working copy.  Would really love to use Histoire on an upcoming project.  If anyone could lend some assistance for Quasar2/Vue3 it would be hugely appreciated.

**Comment by brnsnt** [comment]
I got this working with a few adjustments around the imports. Now i am able to use it in `histoire.config.ts` directly.  

```js 
import { defineConfig } from 'histoire';
import { HstVue } from '@histoire/plugin-vue';
import { quasarViteConfig } from './src/quasar-config';

export default defineConfig({
  plugins: [HstVue()],
  vite: quasarViteConfig("@quasar/app-vite"),
});
``` 

But `histoire dev` gives me then the following error: 
```
Error while collecting story /home/.../Button.story.vue:
TypeError: plugin.load.call is not a function
    at Object.load (/home/.../node_modules/vite/dist/node/chunks/dep-c9998dc6.js:39293:50)
    at doTransform (/home/.../node_modules/vite/dist/node/chunks/dep-c9998dc6.js:49976:46)
```

@IlCallo Any idea on what might be the problem now? Thank you.

**Comment by IlCallo** [comment]
Not really, all these problems are probably related to how Historie manage and override Quasar configuration
We had the same problem with Cypress and we had to dig into their codebase and find the bug in their code, but we don't have time to do it for all the projects

In these cases I'd just try to use historie unminified bundle, then set the debugger or console.log around to understand what's actually happening underneath and what is making Historie fail

In this particular case, that error may be generated in case Historie is treating `quasarViteconfig` result as a plugin and not a Promise resolving to a plugin, aka it doesn't support async config

I'd suggest to always share a repro with your findings so far, so that other users can pick up from where you came and you can investigate the problem collaboratively

**Comment by Akryum** [comment]
Could someone post a runnable repro so I can take a look at this? Thanks :pray:

**Comment by brnsnt** [comment]
I'm deeply sorry for the delay. Was busy week, but got bit further on this. 

Demo project is located here https://github.com/brnsnt/quasar-histoire-demo

:pray: Thank you @IlCallo for pointing me in the right direction, it seems it was still an issue with loading the configuration. 

I did now load the quasar-vite config in a Histoire Plugin, similar to how it is done for the Nuxt-Plugin, and this seems to load it correctly. 

https://github.com/brnsnt/quasar-histoire-demo/blob/main/src/histoire-plugin-quasar.ts

But Quasar Components still can't be used. When I import and install the Quasar Vue Plugin in the [setupfile](https://github.com/brnsnt/quasar-histoire-demo/blob/main/src/histoire.setup.ts) I get the following error. 

```
Error while collecting story /home/brns/git/quasar-histoire/quasar-project/src/components/ExampleComponent.story.vue:
TypeError: Cannot read properties of undefined (reading 'prototype')
    at /home/brns/git/quasar-histoire/quasar-project/node_modules/quasar/dist/quasar.esm.prod.js:7:22681
    at async ViteNodeRunner.directRequest (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:251:5)
    at async ViteNodeRunner.cachedRequest (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:128:12)
    at async request (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:151:16)
    at async /home/brns/git/quasar-histoire/quasar-project/src/histoire.setup.ts:5:31
    at async ViteNodeRunner.directRequest (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:251:5)
    at async ViteNodeRunner.cachedRequest (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:128:12)
    at async request (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:151:16)
    at async /home/brns/git/quasar-histoire/quasar-project/node_modules/@histoire/plugin-vue/dist/bundled/client/server/run.js:3:31
    at async ViteNodeRunner.directRequest (file:///home/brns/git/quasar-histoire/quasar-project/node_modules/vite-node/dist/client.mjs:251:5)
```

**Comment by MarlonVictor** [comment]
I made a simple example of using histoire together with quasar and it returns this error. I really want to use it with quasar, please help me 🙏

https://stackblitz.com/edit/quasarframework-cmamo7

**Comment by patrickmonteiro** [comment]
I would love to use histoire with quasar, but it seems the integration still doesn't work.

**Comment by onexdata** [comment]
> Not really, all these problems are probably related to how Historie manage and override Quasar configuration We had the same problem with Cypress and we had to dig into their codebase and find the bug in their code, but we don't have time to do it for all the projects
> 
> In these cases I'd just try to use historie unminified bundle, then set the debugger or console.log around to understand what's actually happening underneath and what is making Historie fail
> 
> In this particular case, that error may be generated in case Historie is treating `quasarViteconfig` result as a plugin and not a Promise resolving to a plugin, aka it doesn't support async config
> 
> I'd suggest to always share a repro with your findings so far, so that other users can pick up from where you came and you can investigate the problem collaboratively

Any update on this? It sounds like from this comment, the Historie team is assuming this is a bug in Quasar without checking to see if it's true and is officially leaving it to the Quasar community to try and figure out... It looks like the Quasar community is trying but unable to find out the issue. While we're familiar with Quasar, we aren't familiar with Historie as we're trying to use it but can't, and certainly not even in the same universe of familiarity as the Historie devs are. Some help or insight into Historie and how it's doing things seems not only helpful, but required for Historie to ever support Quasar.

Quasar is the #2 UI kit in Vue, and Historie is a UI tool for Vue.  It would seem Historie would want to work with Quasar.

Is it really fair for the Historie team to say to anyone asking why Historie doesn't work with a major Vue platform "this is probably a problem with that platform, so, you figure it out." ?

What are the chances that Historie has no implementation issues or bugs, and it's always the other platforms?

Even if that actually is true, is it a healthy stance to take? Quasar is a mjaor pillar in Vue, and Historie is a Vue tool. Is it possible we can get help so we can adopt and love Historie too? Or is the Quasar community a minority or maginalized demographic in Historie leadership's eyes?

**Comment by Heartnett** [comment]
I'm facing a similar issue, but my setup is Nuxt + Quasar + Vue Macros + Histoire.

**Comment by patrickmonteiro** [comment]
Almost 2 years later and no update on this?

**Comment by jclaveau** [comment]
> Almost 2 years later and no update on this?

A part of the job is in the scope of the Quasar team for Quasar v3: https://github.com/orgs/quasarframework/projects/2/views/1?pane=issue&itemId=5779563

**Comment by IlCallo** [comment]
We actually expose a dedicated config for testing in new app-vite and app-webpack packages major version (currently in beta), but it's still an async function, due to how Quasar config works:
- https://github.com/quasarframework/quasar/blob/dev/app-vite/lib/testing.js
- https://github.com/quasarframework/quasar/blob/dev/app-webpack/lib/testing.js

**Comment by Dtsiantaris** [comment]
Hey @chrisvfritz,

With this solution, if you have any quasar app-extensions, they are not able to resolve correctly. 
Currently trying to find out

**Comment by 50rayn** [comment]
[Poveste](https://github.com/poveste-dev/poveste) (a maintained fork of histoire) ships Quasar support as of 0.9.0 — [@poveste/plugin-quasar](https://npmx.dev/package/@poveste/plugin-quasar). The blocker in this thread was that Quasar's Vite config is only available asynchronously; poveste's plugin API awaits defaultConfig, so it resolves.

One gotcha worth knowing up front: boot files don't run in a story, so you name them via `setupQuasar({ boot })` — otherwise an app extension's components are just missing, with a green build and no error.

Tested against a real npm init quasar app with layouts, router, SCSS variables and @quasar/qcalendar as an app extension. Docs: https://poveste.dev/guide/config.html
