### ISSUE TITLE
Issues when histoire.config.ts is not located in project root 

### ISSUE THREAD

**Issue by clowNay** [histoire-dev/histoire#167]
### Describe the bug

I run in to several issues with the following directory structure.

```
<root>
    <playground>
        app.vue
        nuxt.config.ts
        histoire.config.ts
    </playground>
    package.json
    ...etc
</root>
```

```
Error while collecting story /Users/andreasquist/Sites/ui/playground/components/UI-Alert.story.vue:
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
    at formatError (/Users/andreasquist/Sites/ui/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39055:46)
    at TransformContext.error (/Users/andreasquist/Sites/ui/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39051:19)
    at TransformContext.transform (/Users/andreasquist/Sites/ui/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58269:22)
    at async Object.transform (/Users/andreasquist/Sites/ui/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39292:30)
    at async doTransform (/Users/andreasquist/Sites/ui/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50012:29)
```

After that I moved the `histoire.config.ts` to the `<root>` and then it worked. Why does it need to be in the root folder?

### Reproduction

Move histoire.config.file to folder

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 22.14 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 89.0.2
    Safari: 15.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NozomuIkuta** [comment]
@clowNay 

Currently, Histoire looks for its config file(s) only at the current working directory (i.e. usually project root).

For example, when you run `histoire dev` command as in your reproduction link:

https://github.com/histoire-dev/histoire/blob/a760adf3a1997852bbb35b88e1aae4609401fb2e/packages/histoire/src/node/bin.ts#L15-L21

https://github.com/histoire-dev/histoire/blob/a760adf3a1997852bbb35b88e1aae4609401fb2e/packages/histoire/src/node/commands/dev.ts#L49

https://github.com/histoire-dev/histoire/blob/2fb86a248902246eb7d1a1255d3281439c4ad105/packages/histoire/src/node/config.ts#L282-L291

If you want to change this behavior, it would be a feature request.

**Comment by clowNay** [comment]
@NozomuIkuta I think that behaviour should be changed or at least provide a way of defining where config file is located with an argument.
