### ISSUE TITLE
Cannot find module 'tailwindcss/defaultTheme' in vue 3 example

### ISSUE THREAD

**Issue by yooouuri** [histoire-dev/histoire#176]
### Describe the bug

Cannot run the Vue 3 example from this repo.

It complains about missing a tailwind module or something. Even when I run `yarn add tailwind` it doesn't change anything...

### Reproduction

```bash
$ git clone https://github.com/histoire-dev/histoire.git
$ cd histoire/examples/vue3
$ yarn
$ yarn story:dev
```

Result:

```
yarn story:dev   
yarn run v1.22.19
$ histoire dev
Port 3000 is in use, trying another one...
  > Local: http://localhost:3001/
  > Network: use `--host` to expose
Error while loading module /Users/youri/dev/histoire/tailwind.config.cjs:
Error: Cannot find module 'tailwindcss/defaultTheme'
Require stack:
- /Users/youri/dev/histoire/tailwind.config.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/youri/dev/histoire/tailwind.config.cjs:4:22
    at ViteNodeRunner.directRequest (file:///Users/youri/dev/histoire/examples/vue3/node_modules/vite-node/dist/client-e36231b1.js:159:11)
    at async ViteNodeRunner.cachedRequest (file:///Users/youri/dev/histoire/examples/vue3/node_modules/vite-node/dist/client-e36231b1.js:73:12)
    at async ViteNodeRunner.executeFile (file:///Users/youri/dev/histoire/examples/vue3/node_modules/vite-node/dist/client-e36231b1.js:60:12)
    at async Object.loadModule (file:///Users/youri/dev/histoire/examples/vue3/node_modules/histoire/dist/node/load.js:22:28)
    at async generate (file:///Users/youri/dev/histoire/examples/vue3/node_modules/histoire/dist/node/builtin-plugins/tailwind-tokens.js:18:36)
[Plugin:tailwind-tokens] Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tailwindcss' imported from /Users/youri/dev/histoire/examples/vue3/node_modules/histoire/dist/node/builtin-plugins/tailwind-tokens.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at generate (file:///Users/youri/dev/histoire/examples/vue3/node_modules/histoire/dist/node/builtin-plugins/tailwind-tokens.js:19:48)
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 330.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: ^2.3.1 => 2.3.3
    histoire: workspace:* => 0.7.9
    vite: ^2.9.1 => 2.9.14
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yooouuri** [comment]
@Akryum don't know but as far as I know, it should not matter if I use yarn or pnpm?
