### ISSUE TITLE
Initial state overwritten when coming back to story

### ISSUE THREAD

**Issue by victorlmneves** [histoire-dev/histoire#228]
### Describe the bug

Creating a new state on Controls throws an error when switching between existing states.
It switches once, and then it no longer is possible to switch back to another option.

```
state.js?v=f51ce856:6 DOMException: Failed to execute 'structuredClone' on 'Window': #<Object> could not be cloned.
    at clone (http://localhost:6600/node_modules/@histoire/shared/dist/state.js?v=f51ce856:3:16)
    at applyPreset (http://localhost:6600/node_modules/histoire/dist/bundled/components/panel/StatePresets.js:45:41)
    at createVNode.onSelect._cache.<computed>._cache.<computed> (http://localhost:6600/node_modules/histoire/dist/bundled/components/panel/StatePresets.js:115:57)
    at callWithErrorHandling (http://localhost:6600/node_modules/@histoire/vendors/dist/client/vue.runtime.esm-bundler.js?v=f51ce856:1993:22)
    at callWithAsyncErrorHandling (http://localhost:6600/node_modules/@histoire/vendors/dist/client/vue.runtime.esm-bundler.js?v=f51ce856:2002:21)
    at emit$1 (http://localhost:6600/node_modules/@histoire/vendors/dist/client/vue.runtime.esm-bundler.js?v=f51ce856:2559:9)
    at http://localhost:6600/node_modules/@histoire/vendors/dist/client/vue.runtime.esm-bundler.js?v=f51ce856:9181:53
    at selectValue (http://localhost:6600/node_modules/histoire/dist/bundled/components/base/BaseSelect.js:45:7)
    at onClick (http://localhost:6600/node_modules/histoire/dist/bundled/components/base/BaseSelect.js:58:38)
    at callWithErrorHandling (http://localhost:6600/node_modules/@histoire/vendors/dist/client/vue.runtime.esm-bundler.js?v=f51ce856:1993:22) 'Fallback to JSON cloning'
```

### Reproduction

Just open one of the existing stories, create a new state on the Controls, and switch between them.

https://stackblitz.com/edit/histoire-vue3-starter-uapwc2

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 219.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 104.1.42.86
    Chrome: 103.0.5060.134
    Firefox: 103.0.1
    Safari: 15.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Does it works anyway? This a warning that has a fallback when the browser can't do a structured clone of your state.

**Comment by victorlmneves** [comment]
@Akryum it works while you are on the story. If you go to a different story and then return to the story it no longer switches the states

**Comment by Akryum** [comment]
Looks like the issue is in reality "the initial state is not the initial one but the one from last state when coming back to the story"

**Comment by Akryum** [comment]
I've implemented a series of improvements that should fix this:
- https://github.com/histoire-dev/histoire/commit/10b1b4b2f521c966248f81d84e24885286c6e23d
- https://github.com/histoire-dev/histoire/commit/e31002d534647115d61a6a66a3b68f7909dc9568
- https://github.com/histoire-dev/histoire/commit/4f52b45398cce5cbfc3d66e2380bd138b061bcd9

**Comment by victorlmneves** [comment]
thanks @Akryum
