### ISSUE TITLE
v0.10.1 [svelte] ... pnpm story:dev error

### ISSUE THREAD

**Issue by oneezy** [histoire-dev/histoire#239]
### Describe the bug

for svelte example i had `0.10.0` working but with `0.10.1` i see this error when running `pnpm story:dev`

![image](https://user-images.githubusercontent.com/7369575/184460730-225e915d-b2af-4db0-9f76-f92b6c505240.png)

```
7:35:06 PM [vite] Internal server error: Failed to resolve import "@histoire/plugin-svelte/assets/histoire-svelte.svg" from "..\..\..\..\$histoire-config-resolved". Does the file exist?
  Plugin: vite:import-analysis
  File: /$histoire-config-resolved
  1  |  export const config = {"plugins":[{"name":"builtin:tailwind-tokens"},{"name":"builtin:vanilla-support","supportPlugin":{"id":"vanilla","moduleName":"C:/Users/oneezy/Desktop/test/node_modules/.pnpm/histoire@0.10.1_vite@3.0.7/node_modules/histoire/dist/node/builtin-plugins/vanilla-support","setupFn":"setupVanilla"}},{"name":"@histoire/plugin-svelte","supportPlugin":{"id":"svelte3","moduleName":"@histoire/plugin-svelte","setupFn":"setupSvelte3"}}],"outDir":"C:/Users/oneezy/Desktop/test/.histoire/dist","storyMatch":["**/*.story.vue","**/*.story.svelte"],"storyIgnored":["**/node_modules/**","**/dist/**"],"supportMatch":[{"id":"vanilla","patterns":["**/*.js"],"pluginIds":["vanilla"]},{"id":"svelte","patterns":["**/*.svelte"],"pluginIds":["svelte3"]}],"tree":{"file":"title","order":"asc","groups":[{"id":"top","title":""}]},"theme":{"title":"Histoire","colors":{"primary":{"50":"#fff7ed","100":"#ffedd5","200":"#fed7aa","300":"#fdba74","400":"#fb923c","500":"#f97316","600":"#ea580c","700":"#c2410c","800":"#9a3412","900":"#7c2d12"},"gray":{"50":"#fafafa","100":"#f4f4f5","200":"#e4e4e7","300":"#d4d4d8","400":"#a1a1aa","500":"#71717a","600":"#52525b","700":"#3f3f46","750":"#323238","800":"#27272a","850":"#1f1f21","900":"#18181b","950":"#101012"}},"logo":{"square":"@histoire/plugin-svelte/assets/histoire-svelte.svg","light":"@histoire/plugin-svelte/assets/histoire-svelte-text.svg","dark":"@histoire/plugin-svelte/assets/histoire-svelte-text.svg"}},"responsivePresets":[{"label":"Mobile (Small)","width":320,"height":560},{"label":"Mobile (Medium)","width":360,"height":640},{"label":"Mobile (Large)","width":414,"height":896},{"label":"Tablet","width":768,"height":1024},{"label":"Laptop (Small)","width":1024,"height":null},{"label":"Laptop (Large)","width":1366,"height":null},{"label":"Desktop","width":1920,"height":null},{"label":"4K","width":3840,"height":null}],"backgroundPresets":[{"label":"Transparent","color":"transparent"},{"label":"White","color":"#fff"},{"label":"Light gray","color":"#aaa"},{"label":"Dark gray","color":"#333"},{"label":"Black","color":"#000"}],"sandboxDarkClass":"dark","routerMode":"history"}  2  |  import Logo_square from '@histoire/plugin-svelte/assets/histoire-svelte.svg'     |                           ^  3  |  import Logo_light from '@histoire/plugin-svelte/assets/histoire-svelte-text.svg'  4  |  import Logo_dark from '@histoire/plugin-svelte/assets/histoire-svelte-text.svg'      at formatError (file:///C:/Users/oneezy/Desktop/test/node_modules/.pnpm/vite@3.0.7/node_modules/vite/dist/node/chunks/dep-0f13c890.js:35044:46)      at TransformContext.error (file:///C:/Users/oneezy/Desktop/test/node_modules/.pnpm/vite@3.0.7/node_modules/vite/dist/node/chunks/dep-0f13c890.js:35040:19)      at normalizeUrl (file:///C:/Users/oneezy/Desktop/test/node_modules/.pnpm/vite@3.0.7/node_modules/vite/dist/node/chunks/dep-0f13c890.js:40248:33)      at processTicksAndRejections (node:internal/process/task_queues:96:5)      at async TransformContext.transform (file:///C:/Users/oneezy/Desktop/test/node_modules/.pnpm/vite@3.0.7/node_modules/vite/dist/node/chunks/dep-0f13c890.js:40382:47)      at async Object.transform (file:///C:/Users/oneezy/Desktop/test/node_modules/.pnpm/vite@3.0.7/node_modules/vite/dist/node/chunks/dep-0f13c890.js:35293:30)      at async loadAndTransform (file:///C:/Users/oneezy/Desktop/test/node_modules/.pnpm/vite@3.0.7/node_modules/vite/dist/node/chunks/dep-0f13c890.js:39879:29)
```

### Reproduction

https://github.com/oneezy/histoire-svelte/tree/0.10.1-bug

(steps inside `README.md`)

### System Info

```shell
- Windows 11
- node v16.13.2
- pnpm 7.9.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oneezy** [comment]
closing. appears to be fixed from this end

**Comment by oneezy** [comment]
closed the issue to soon. I recorded a quick video to show the problem in action.

[histoire-0.10.1-svelte-bug.webm](https://user-images.githubusercontent.com/7369575/184461389-c2a38db6-905b-41fd-9e3a-ae879d34b8dc.webm)
