### ISSUE TITLE
tailwind-tokens Error: Path contains invalid characters

### ISSUE THREAD

**Issue by llbarr1** [histoire-dev/histoire#256]
### Describe the bug

When running `story:dev` on a Windows 10 machine I get the following error when generating the Tailwind tokens:

```
[Plugin:builtin:tailwind-tokens] Error: Path contains invalid characters: C:/Dev/histoire/node_modules/.histoire/plugins/builtin:tailwind-tokens    
   at checkPath (C:\Dev\histoire\node_modules\fs-extra\lib\mkdirs\utils.js:16:21)
    at Object.module.exports.makeDir (C:\Dev\histoire\node_modules\fs-extra\lib\mkdirs\make-dir.js:13:3)
    at Object.defineProperty.value (C:\Dev\histoire\node_modules\fs-extra\node_modules\universalify\index.js:21:45)
    at generate (file:///C:/Dev/histoire/node_modules/histoire/dist/node/builtin-plugins/tailwind-tokens.js:17:26)
    at FSWatcher.<anonymous> (file:///C:/Dev/histoire/node_modules/histoire/dist/node/builtin-plugins/tailwind-tokens.js:62:38)
    at FSWatcher.emit (node:events:526:28)
    at FSWatcher.emitWithAll (C:\Dev\histoire\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (C:\Dev\histoire\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (C:\Dev\histoire\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (C:\Dev\histoire\node_modules\chokidar\lib\nodefs-handler.js:637:21)
```

The server still finishes loading, but the Design System section is empty:

![image](https://user-images.githubusercontent.com/68648786/185637643-8e2d5aad-3ebc-4b6b-a5c7-90bb66dcc789.png)

The same error appears when trying to run `story:build`.

### Reproduction

Install histoire on a Windows 10 machine
Run story:dev

### System Info

```shell
Node 16.14.2
npm 7.21.0
Windows 10 Version 20H2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oneezy** [comment]
Can confirm on Windows 11 as well

**Comment by oneezy** [comment]
@Akryum gave this advice and it fixed the issue
> _You can try editing the `pluginTempDir` computation in `node_modules/histoire/dist/node/plugin.js` and put_
```js
this.plugin.name.replace(/:/g, '_')
```
