### ISSUE TITLE
Percy failing to build / compile

### ISSUE THREAD

**Issue by Archetipo95** [histoire-dev/histoire#330]
### Describe the bug

I was trying histoire with Nuxt 3 and Nuxt Tailwind, and I wanted to add Percy for visual regression. I followed the guide as described here [https://github.com/histoire-dev/histoire/tree/main/packages/histoire-plugin-percy](https://github.com/histoire-dev/histoire/tree/main/packages/histoire-plugin-percy).

I was not able to make it work. This is the log when it fails:

```
% yarn test:percy                                                                         
$ percy exec -- pnpm run story:build
[percy] Successfully downloaded Chromium 929475
[percy] Percy has started!
[percy] Running "pnpm run story:build"

> @ story:build /..../nuxt-histoire
> histoire build

ℹ Using Tailwind CSS from ~/assets/scss/main.scss
ℹ Vite client warmed up in 1693ms
✔ Nitro built in 1426 ms
/........../node_modules/@histoire/plugin-percy/dist/index.js:20
      const browser = await puppeteer.launch();
                                      ^

TypeError: Cannot read properties of undefined (reading 'launch')
    at Object.onBuild (/........../node_modules/@histoire/plugin-percy/dist/index.js:20:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async build (file:///........../node_modules/histoire/dist/node/build.js:43:13)
    at async buildCommand (file:///........../node_modules/histoire/dist/node/commands/build.js:7:5)
 ERROR  Command failed with exit code 1.
[percy] Finalized build #1: https://percy.io/7ae011fa/nuxt-histoire/builds/22228121
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction

If you want to try I made a repository: [https://github.com/Archetipo95/nuxt-histoire](https://github.com/Archetipo95/nuxt-histoire)

Just add your percy token (as described [here](https://docs.percy.io/docs/storybook#usage)) and run the command `yarn percy:test`.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 98.14 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Edge: 98.0.1108.62
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @histoire/plugin-nuxt: ^0.11.5 => 0.11.5 
    @histoire/plugin-percy: ^0.11.5 => 0.11.5 
    @histoire/plugin-vue: ^0.11.5 => 0.11.5 
    histoire: ^0.11.5 => 0.11.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Archetipo95** [comment]
I updated the repository with the last version of histoire and Nuxt 3
