### ISSUE TITLE
Failed to load virtual:$histoire-setup

### ISSUE THREAD

**Issue by Neophen** [histoire-dev/histoire#354]
### Describe the bug

Can not launch basic histoire with the latest vite/histoire/vue3
basically moving the setupFile: './src/histoire.setup.ts', causes the issue

```
Error while collecting story /home/projects/histoire-vue3-starter-kkheq6/src/BaseButton.story.vue:
Error: [vite-node] Failed to load virtual:$histoire-setup
    at ViteNodeRunner.directRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:197:13)
    at async ViteNodeRunner.cachedRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:145:12)
    at async request (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:168:16)
    at async eval (/home/projects/histoire-vue3-starter-kkheq6/node_modules/@histoire/plugin-vue/dist/bundled/client/server/run.js:3:31)
    at async ViteNodeRunner.directRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:268:5)
    at async ViteNodeRunner.cachedRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:145:12)
    at async request (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:168:16)
    at async eval (/home/projects/histoire-vue3-starter-kkheq6/node_modules/@histoire/plugin-vue/dist/bundled/client/server.js:1:238)
    at async ViteNodeRunner.directRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:268:5)
    at async ViteNodeRunner.cachedRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:145:12)
Error while collecting story /home/projects/histoire-vue3-starter-kkheq6/src/InjectDemo.story.vue:
Error: [vite-node] Failed to load virtual:$histoire-setup
    at ViteNodeRunner.directRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:197:13)
    at async ViteNodeRunner.cachedRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:145:12)
    at async request (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:168:16)
    at async eval (/home/projects/histoire-vue3-starter-kkheq6/node_modules/@histoire/plugin-vue/dist/bundled/client/server/run.js:3:31)
    at async ViteNodeRunner.directRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:268:5)
    at async ViteNodeRunner.cachedRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:145:12)
    at async request (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:168:16)
    at async eval (/home/projects/histoire-vue3-starter-kkheq6/node_modules/@histoire/plugin-vue/dist/bundled/client/server.js:1:238)
    at async ViteNodeRunner.directRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:268:5)
    at async ViteNodeRunner.cachedRequest (file:///home/projects/histoire-vue3-starter-kkheq6/node_modules/vite-node/dist/client.mjs:145:12)
```

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-ecpfxc

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/plugin-vue: ^0.11.6 => 0.11.6 
    @vitejs/plugin-vue: ^3.1.2 => 3.1.2 
    histoire: ^0.11.6 => 0.11.6 
    vite: ^3.1.8 => 3.2.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Hey! I've tried reproducing the issue but I haven't been able to: https://stackblitz.com/edit/histoire-vue3-starter-m1j6ao?file=vite.config.ts,histoire.setup.ts,src%2Fmeow.setup.ts,histoire.config.ts

Could you post an updated stackblitz that demonstrates the issue?

**Comment by Neophen** [comment]
Can't reproduce it anymore
