### ISSUE TITLE
🟧 Sveltekit: Can't import built-in Sveltekit modules in components (i.e. $path)

### ISSUE THREAD

**Issue by oneezy** [histoire-dev/histoire#384]
### Describe the bug

When trying to import [Sveltekit Modules](https://kit.svelte.dev/docs/modules#$app-stores) such as the `$path` store in a component, 

❌ I get an error in **Histoire** `(port 6006)`
✅ I don't get an error in **Sveltekit** `(port 5173)`.

>  
> _**Example:** a component that displays the **\<PageTitle />**_
> _**Output:** `"histoire-dev/histoire/issues/384"`_
>  
```html
<!-- PageTitle .svelte -->
<script>
  import { page } from '$app/stores'
</script>

<h1>{$page.url.pathname}</h1>
```
[sveltekit-histoire-bug.webm](https://user-images.githubusercontent.com/7369575/205033810-e3ad6e6d-d70a-4270-8a0f-2d699562f764.webm)

## Error
![image](https://user-images.githubusercontent.com/7369575/205033688-aecf1d1f-dbf8-4afc-b1a4-283fbbcd887c.png)

```diff
> oneezy@oneezy MINGW64 ~/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro (main)
$ pnpm story

> histoire-sveltekit@0.0.1 story C:\Users\oneezy\Desktop\www\10.Repros\indaco-histoire-sveltekit-repro
> svelte-kit sync && histoire dev

  ➜  Local:   http://localhost:6006/
  ➜  Network: use --host to expose
Collect stories start all
Failed to resolve import "$app/stores" from "src\lib\components\URLpath\URLpath.svelte". Does the file exist?
Error while collecting story C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/src/stories/URLpath/URLpath.story.svelte:
Error: Failed to resolve import "$app/stores" from "src\lib\components\URLpath\URLpath.svelte". Does the file exist?
    at formatError (file:///C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:40854:46)
    at TransformContext.error (file:///C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:40850:19)
    at normalizeUrl (file:///C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:37587:33)
    at async TransformContext.transform (file:///C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:37720:47)
    at async Object.transform (file:///C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:41103:30)
    at async loadAndTransform (file:///C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/vite@3.1.4/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:37365:29)
Collect stories end 3952 ms
The request url "C:/Users/oneezy/Desktop/www/2.Starters/monorepo/node_modules/.pnpm/@histoire+app@0.11.7_vite@3.2.4/node_modules/@histoire/app/dist/bundle-main.js" is outside of Vite serving allow list.

- C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.pnpm/@histoire+app@0.11.0_vite@3.1.4/node_modules/@histoire/app/dist
- C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro/node_modules/.histoire
- C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro
- C:/Users/oneezy/Desktop/www/10.Repros/indaco-histoire-sveltekit-repro

Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.
```

### Reproduction

**Stackblitz Repro:**
https://stackblitz.com/edit/sveltejs-kit-template-default-cszmd5?file=src/lib/components/PageTitle/PageTitle.svelte

![image](https://user-images.githubusercontent.com/7369575/205184945-d5127205-0a67-41da-aea3-9742ba71507a.png)

### System Info

```shell
**OS:** Windows 11 Pro (build - 22000.1219)
**Browser:** Chrome - Version 107.0.5304.122 (Official Build) (64-bit)
**Node:** 18.8.0
**PNPM:** 7.17.1
**Terminal:** Git Bash
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oneezy** [comment]
**related issues:**

https://github.com/indaco/histoire-sveltekit/issues/2
https://github.com/histoire-dev/histoire/issues/241
https://github.com/histoire-dev/histoire/issues/278
https://github.com/histoire-dev/histoire/pull/281
https://github.com/histoire-dev/histoire/issues/321
https://github.com/histoire-dev/histoire/issues/375

**Comment by benzara-tahar** [comment]
Am having the same issue, I am trying to resolve the `$app/stores` inside the `histoire.config.js` but I don't know where is the file exporting it 
Any idea?

```diff
import { defineConfig, defaultColors } from 'histoire';
import { HstSvelte } from '@histoire/plugin-svelte';
import { resolve } from 'path';

export default defineConfig({
  setupFile: './histoire-setup.js',
  theme: {
    title: 'Qomino Design System',
    colors: {
      primary: defaultColors.cyan,
    },
    favicon: './static/favicon.svg',
  },
  vite: {
    resolve: {

      alias: {
         '$lib': resolve('.src/lib'),
         '@components': resolve('./src/lib/components'),
         '@utils': resolve('./src/lib/utils'),
         '@icons': resolve('./src/lib/icons'),
+        '$app/stores': resolve('./node_modules/@sveltejs/kit/types'), // <-- how to resove this?
      },

    }
  },

  plugins: [HstSvelte()],
});

```

**Comment by benzara-tahar** [comment]
One workaround is to mock the modules you need , for my cases i only used `$page.url` so I mocked that
![image](https://user-images.githubusercontent.com/71077112/206246496-fb46e31f-4db6-40a6-9b9a-5ccc710f21d8.png)
![image](https://user-images.githubusercontent.com/71077112/206246675-ae6a9263-6c74-452f-ba20-d7cf49dea449.png)

**Comment by oneezy** [comment]
@benzara-tahar  Thanks for posting a possible workaround!

I was sifting through the docs earlier and saw this so figured I'd post it here

https://kit.svelte.dev/docs/packaging

![Screenshot_20221210-000122](https://user-images.githubusercontent.com/7369575/206838241-5049cbc0-90f0-480b-99ce-0c7e8e6ee4f5.png)

**Comment by benmccann** [comment]
I hope this will be fixed if we leave SvelteKit's setup plugin in place and remove it's compile plugin. See my comment here: https://github.com/histoire-dev/histoire/pull/393#discussion_r1045263380

**Comment by oneezy** [comment]
Thanks for giving this one attention @benmccann !

Sveltekit + Histoire are a match made in heaven :)

I'll follow that thread and help test where I can

**Comment by oneezy** [comment]
@Akryum , this bug still exists

**Comment by benmccann** [comment]
Some SvelteKit modules will work and some won't. You can see a summary here: https://github.com/storybookjs/storybook/tree/next/code/frameworks/sveltekit#supported-features
