### ISSUE TITLE
fails to load stories below project root

### ISSUE THREAD

**Issue by luckydye** [histoire-dev/histoire#403]
### Describe the bug

When defining match storyMatch below the root directory of the histoire project, in for example a monorepo, build and dev will throw an error of "Failed to load url.".

### Reproduction

Create a project with this folder structure:
```
├── apps
|  └── test
|     ├── histoire.config.ts
|     └── package.json
├── package.json
├── pnpm-lock.yaml
├── pnpm-workspace.yaml
└── stories
   └── Test.story.vue
```

histoire installed in *apps/test* with:
`pnpm i -D histoire @histoire/plugin-vue`

with this *apps/test/histoire.config.ts*:
```typescript
import { defineConfig } from "histoire";
import { HstVue } from "@histoire/plugin-vue";

export default defineConfig({
  plugins: [HstVue()],
  storyMatch: ["../../stories/*.story.vue"],
});

```

and *stories/Test.story.vue*:
```
<template>
  <Story title="🐱 Meow"> 🐱 </Story>
</template>

```
Then after running `pnpm story:dev` in *apps/test* it will throw:

```
Error while collecting story /Users/tihav/src/atrium-ui/atrium-ui-mono/stories/Test.story.vue:
Error: [vite-node] Failed to load /Users/tihav/src/atrium-ui/atrium-ui-mono/stories/Test.story.vue
    at ViteNodeRunner.directRequest (file:///Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/vite-node@0.23.4/node_modules/vite-node/dist/client.mjs:180:13)
    at async ViteNodeRunner.cachedRequest (file:///Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/vite-node@0.23.4/node_modules/vite-node/dist/client.mjs:128:12)
    at async request (file:///Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/vite-node@0.23.4/node_modules/vite-node/dist/client.mjs:151:16)
    at async v (/Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/@histoire+plugin-vue@0.11.9_vgxee6juai2ux6n5oucjlvgv4a/node_modules/@histoire/plugin-vue/dist/bundled/client/server/run.js:12:26)
    at async run (/Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/histoire@0.11.9_vite@3.2.5/node_modules/histoire/dist/node/collect/run.js:6:20)
    at async default (file:///Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/histoire@0.11.9_vite@3.2.5/node_modules/histoire/dist/node/collect/worker.js:41:5)
    at async file:///Users/tihav/src/atrium-ui/atrium-ui-mono/node_modules/.pnpm/tinypool@0.1.3/node_modules/tinypool/dist/esm/worker.js:96:20
```

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 724.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.0 - ~/.nvm/versions/node/v17.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v17.9.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v17.9.0/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 108.0.5359.124
    Chrome Canary: 110.0.5481.3
    Firefox: 106.0.5
    Safari: 16.1
    Safari Technology Preview: 16.4
  npmPackages:
    @histoire/plugin-vue: ^0.11.9 => 0.11.9 
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    histoire: ^0.11.9 => 0.11.9 
    vite: ^4.0.1 => 4.0.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by luckydye** [comment]
@serkodev Sure thing! Im not sure why I didn't post it here, sry.

For me it was a vite problem.
I needed to allow vite to access the files below its root like this:
```javascript
export default defineConfig({
  ...
  server: {
    fs: {
      allow: ["../../"]
    }
  },
  ...
})
```

**Comment by serkodev** [comment]
@luckydye Thanks! I used your solution to solve my problem.
