### ISSUE TITLE
resolve.alias is not working for $app/stores in sveltekit projects

### ISSUE THREAD

**Issue by EugeneDraitsev** [histoire-dev/histoire#408]
### Describe the bug

I've checked another issues about `$app/stores`, but it seems like I have another issue.
It looks like resolve section in config ignores `$app/stores`:

When I try to use `$app/stores` in my story:

```js
import { page } from '$app/stores';
```
With following `histoire.config.ts`

```js
import { defineConfig } from 'histoire';
import { HstSvelte } from '@histoire/plugin-svelte';
import { resolve } from 'path';

export default defineConfig({
  routerMode: 'hash',
  plugins: [HstSvelte()],
  vite: {
    resolve: {
      alias: {
        '$app/stores': resolve(__dirname, './stores.mjs')
      }
    }
  }
});
```
I get an error:
```
ReferenceError: __SVELTEKIT_APP_VERSION_POLL_INTERVAL__ is not defined
```

It worked fine with Histoire `0.11.2`, vite `3.5.2` and sveltekit beta

### Reproduction

Repo: https://github.com/EugeneDraitsev/histoire-alias-issue
stackblitz (not sure that it works fine): https://stackblitz.com/edit/sveltejs-kit-template-default-2wzudb?file=src%2Flib%2FTest.story.svelte
 
Steps to reproduce: 
1. Clone https://github.com/EugeneDraitsev/histoire-alias-issue or Create new sveltkit project + setup histoire
2. Run `yarn & yarn story:build` - it will work fine 
3. Uncoment `src/lib/Test.story.svelte:3` and run `yarn story:build`
4. See an error!

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 109.0
    Safari: 16.2
  npmPackages:
    @histoire/plugin-svelte: ^0.12.0 => 0.12.0 
    histoire: ^0.12.0 => 0.12.0 
    vite: ^4.0.2 => 4.0.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by madeleineostoja** [comment]
I'm also seeing this with sveltekit 1.0.1 and without any aliases in my histoire config

**Comment by benmccann** [comment]
`__SVELTEKIT_APP_VERSION_POLL_INTERVAL__` is defined in `vite-plugin-sveltekit-setup`: https://github.com/sveltejs/kit/blob/668d2f3785e47b805e1e3df1eb3bc4e234c471f8/packages/kit/src/exports/vite/index.js#L259

I'd expect this to work because it's only `vite-plugin-sveltekit-compile`, which is removed:
https://github.com/histoire-dev/histoire/blob/fbbc58f2700b7ba437c5846032b65239d1c7306c/packages/histoire-plugin-svelte/src/index.ts#L31

I see the reproduction is pinned to SvelteKit 1.0.1: https://github.com/EugeneDraitsev/histoire-alias-issue/blob/0892e0d4795eda660a687792e597a0270163d3bd/package.json#L22

Can you please unpin it, update the reproduction to the latest version, and let me know if it works?

**Comment by EugeneDraitsev** [comment]
Hi @benmccann,

I've update all svelte and histoire dependencies in the repo with example and it still fails with the same error if I uncomment the line with `$app/stores` import:
```
Error while collecting story D:/environment/histoire-alias-issue/src/lib/Test.story.svelte:
ReferenceError: __SVELTEKIT_APP_VERSION_POLL_INTERVAL__ is not defined
    at create_updated_store (file:///D:/environment/histoire-alias-issue/node_modules/@sveltejs/kit/src/runtime/client/utils.js:208:19)
    at file:///D:/environment/histoire-alias-issue/node_modules/@sveltejs/kit/src/runtime/client/singletons.js:20:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async ViteNodeRunner.interopedImport (file:///D:/environment/histoire-alias-issue/node_modules/vite-node/dist/client.mjs:295:28)
    at async ViteNodeRunner.directRequest (file:///D:/environment/histoire-alias-issue/node_modules/vite-node/dist/client.mjs:201:24)
    at async ViteNodeRunner.cachedRequest (file:///D:/environment/histoire-alias-issue/node_modules/vite-node/dist/client.mjs:146:14)
    at async ViteNodeRunner.dependencyRequest (file:///D:/environment/histoire-alias-issue/node_modules/vite-node/dist/client.mjs:181:14)
    at async D:\environment\histoire-alias-issue\src\lib\Test.story.svelte:6:31
```

**Comment by benmccann** [comment]
I wonder if it'd work if you just remove this config?
```
  vite: {
    resolve: {
      alias: {
        '$app/stores': resolve(__dirname, './stores.mjs')
      }
    }
  }
```

I believe `$app/stores` works in Storybook without having to override it: https://github.com/storybookjs/storybook/tree/next/code/frameworks/sveltekit#supported-features

**Comment by EugeneDraitsev** [comment]
Nope, same issue without `vite` section in the `histoire.config.ts`

**Comment by ctwheels** [comment]
I get the same issue trying to use `import { page } from '$app/stores';`

```
Error while collecting story /workspace/web/src/lib/components/Component.story.svelte:
ReferenceError: __sveltekit_eujora is not defined
    at /workspace/web/__sveltekit/paths:1:14
    at ViteNodeRunner.directRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:312:11)
    at async ViteNodeRunner.cachedRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:156:14)
    at async ViteNodeRunner.dependencyRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:204:14)
    at async /workspace/web/node_modules/.pnpm/@sveltejs+kit@1.9.0_svelte@3.55.0+vite@4.0.4/node_modules/@sveltejs/kit/src/runtime/client/utils.js:5:31
    at async ViteNodeRunner.directRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:312:5)
    at async ViteNodeRunner.cachedRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:156:14)
    at async ViteNodeRunner.dependencyRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:204:14)
    at async /workspace/web/node_modules/.pnpm/@sveltejs+kit@1.9.0_svelte@3.55.0+vite@4.0.4/node_modules/@sveltejs/kit/src/runtime/client/singletons.js:3:31
    at async ViteNodeRunner.directRequest (file:///workspace/web/node_modules/.pnpm/vite-node@0.28.4_gneikmxcpj2uc2xuqjosnroj4e/node_modules/vite-node/dist/client.mjs:312:5)
```

**Comment by benmccann** [comment]
@ctwheels your issue is a different one that was recently fixed in SvelteKit. Please update to the latest and it should work
