### ISSUE TITLE
Nuxt plugin from module not loaded

### ISSUE THREAD

**Issue by gaetansenn** [histoire-dev/histoire#415]
### Describe the bug

The `@histoire/plugin-nuxt` start my external module but the plugin is never injected.

### Reproduction

Code: https://github.com/gaetansenn/vunix/tree/main/apps/playground
Preview: https://vunix-playground.netlify.app/story/components-elements-button-story-vue?variantId=_default

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 78.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Please give [v0.15.0] a try and report back if your issue is solved or not :pray:

**Comment by gaetansenn** [comment]
Hey @Akryum I have updated histoire and now the plugin is loaded :)

I have 2 problems:
  - can't use app.config of nuxt as .ts [TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/gaetansenn/Development/dewib/librairies/ui/apps/playground/app.config.ts].
  - get an error of histoire plugin nuxt, logs is at the end.

You can try by cloning the https://github.com/gaetansenn/vunix repository with yarn install;yarn dev:playground
 
```playground:dev: cache bypass, force executing cafe0d0553e0a4a0
playground:dev: $ histoire dev
playground:dev: ℹ Using default Tailwind CSS file from runtime/tailwind.css
playground:dev: ℹ Vite client warmed up in 1099ms
playground:dev: ✔ Nitro built in 1237 ms
playground:dev: Using 5 threads for story collection
playground:dev: Collect stories start all
playground:dev:   ➜  Local:   http://127.0.0.1:6006/
playground:dev:   ➜  Network: use --host to expose
playground:dev: /Users/gaetansenn/Development/dewib/librairies/ui/apps/playground/node_modules/.histoire/plugins/builtin_tailwind-tokens/Tailwind.story.js 1263ms (setup:26ms, execute:11ms, run:1226ms)
playground:dev: call plugin nuxt
playground:dev: components/elements/Button.story.vue 1803ms (setup:25ms, execute:11ms, run:1767ms)
playground:dev: Collect stories end 2184ms
playground:dev: Sourcemap for "/__resolved__virtual:$histoire-theme.css" points to missing source files
playground:dev: Collect stories start all
playground:dev: /Users/gaetansenn/Development/dewib/librairies/ui/apps/playground/node_modules/.histoire/plugins/builtin_tailwind-tokens/Tailwind.story.js 16ms (setup:16ms, execute:0ms, run:0ms)
playground:dev: components/elements/Button.story.vue 23ms (setup:16ms, execute:0ms, run:7ms)
playground:dev: Collect stories end 34ms
playground:dev: ✘ [ERROR] Could not resolve "#app/entry"
playground:dev: 
playground:dev:     ../../node_modules/@histoire/plugin-nuxt/dist/runtime/app-setup.js:44:17:
playground:dev:       44 │     await import('#app/entry');
playground:dev:          ╵                  ~~~~~~~~~~~~
playground:dev: 
playground:dev:   You can mark the path "#app/entry" as external to exclude it from the bundle, which will remove this error. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.
playground:dev: 
playground:dev: 11:46:05 PM [vite] error while updating dependencies:
playground:dev: Error: Build failed with 1 error:
playground:dev: ../../node_modules/@histoire/plugin-nuxt/dist/runtime/app-setup.js:44:17: ERROR: Could not resolve "#app/entry"
playground:dev:     at failureErrorWithLog (/Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
playground:dev:     at /Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
playground:dev:     at runOnEndCallbacks (/Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
playground:dev:     at buildResponseToResult (/Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
playground:dev:     at /Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
playground:dev:     at responseCallbacks.<computed> (/Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
playground:dev:     at handleIncomingPacket (/Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
playground:dev:     at Socket.readFromStdout (/Users/gaetansenn/Development/dewib/librairies/ui/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
playground:dev:     at Socket.emit (node:events:513:28)
playground:dev:     at Socket.emit (node:domain:489:12)
```

**Comment by yshrsmz** [comment]
I got the same error after upgrading to histoire 0.15.x.
Could this be a compatibility issue with the latest version of Nuxt3(3.2.x)?

`@nuxt/kit` of `@histoire/plugin-nuxt` is resolved to 3.1.2, so there could be some issue.

https://github.com/histoire-dev/histoire/blob/9f9272158c42e0eac19797c940a25a600acfe975/pnpm-lock.yaml#L467
