### ISSUE TITLE
ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by CavalcanteLeo** [histoire-dev/histoire#478]
### Describe the bug

I'm facing a error and all my stories is not showing, but the tailwind stories are fine

```shell
Error while collecting story /Users/leonardocavalcante/projects/XXXX-nuxt/components/AutoImport.story.vue:
ReferenceError: Vue is not defined
    at Object.<anonymous> (/Users/leonardocavalcante/projects/XXXX-nuxt/node_modules/.pnpm/vue-multiselect@3.0.0-beta.1/node_modules/vue-multiselect/dist/vue-multiselect.js:1350:7)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Error while collecting story /Users/leonardocavalcante/projects/XXXX-nuxt/components/Button/Button.story.vue:
ReferenceError: Vue is not defined
    at Object.<anonymous> (/Users/leonardocavalcante/projects/XXXX-nuxt/node_modules/.pnpm/vue-multiselect@3.0.0-beta.1/node_modules/vue-multiselect/dist/vue-multiselect.js:1350:7)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Reproduction

vite.config.ts:
```ts
import { defineConfig } from 'vite'
import postcssNesting from 'postcss-nesting'
import atImport from 'postcss-import'

export default defineConfig({
  optimizeDeps: {
    // include: ['@fawmi/vue-google-maps', 'fast-deep-equal'],
  },
  css: {
    postcss: {
      plugins: [postcssNesting, atImport],
    },
  },
})
```

histoire.config.ts
```ts
import { defineConfig } from 'histoire'
import { HstVue } from '@histoire/plugin-vue'
import { HstNuxt } from '@histoire/plugin-nuxt'

export default defineConfig({
  plugins: [HstVue(), HstNuxt()],
  storyIgnored: [
    '**/node_modules/**',
    '**/dist/**',
    '**/vue-multiselect@3.0.0-beta.1/**',
  ],
})
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 2.33 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.02.20.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
  npmPackages:
    @histoire/plugin-nuxt: ^0.15.8 => 0.15.8
    @histoire/plugin-vue: ^0.15.8 => 0.15.8
    histoire: ^0.15.8 => 0.15.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by eladcandroid** [comment]
Show your AutoImport.story.vue file
