### ISSUE TITLE
Window is not defined when trying to generate the build

### ISSUE THREAD

**Issue by hallefsantos** [histoire-dev/histoire#487]
### Describe the bug

I'm trying to generate the build and I'm getting error, probably the problem is with the `window is not defined`, any way to fix this? 

```
Error while collecting story /Users/andrewwei/dev/epsilon/src/Shared/CopyClipboard/CopyClipboard.story.svelte:
ReferenceError: window is not defined
    at getWindow (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:18:109)
    at isElement (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:46:27)
    at /Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:485:59
    at Array.filter (<anonymous>)
    at getClippingElementAncestors (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:485:46)
    at Object.getClippingRect (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:517:71)
    at detectOverflow (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:245:62)
    at async fn (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:563:24)
    at async Module.computePosition (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:126:9)

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
ReferenceError [Error]: window is not defined
    at getWindow (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:18:109)
    at isElement (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:46:27)
    at /Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:485:59
    at Array.filter (<anonymous>)
    at getClippingElementAncestors (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:485:46)
    at Object.getClippingRect (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js:517:71)
    at detectOverflow (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:245:62)
    at async fn (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:563:24)
    at async Module.computePosition (/Users/andrewwei/dev/epsilon/node_modules/@floating-ui/core/dist/floating-ui.core.esm.js:126:9)
```

### Reproduction

This happens when I tried to generate the build for production.

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
    Firefox: 110.0
    Safari: 16.1
  npmPackages:
    vite: ^4.0.0 => 4.1.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Javid-Izadfar** [comment]
any updates?

**Comment by DIntriligator** [comment]
+1

**Comment by s3bc40** [comment]
We have the same error on our side 
```bash
Error while collecting story /ourPath :
ReferenceError: window is not defined
    at T (/builds/assessfirst/frontend/af-library/node_modules/.pnpm/webfontloader@1.6.28/node_modules/webfontloader/webfontloader.js:6:186)
    at U (/builds/assessfirst/frontend/af-library/node_modules/.pnpm/webfontloader@1.6.28/node_modules/webfontloader/webfontloader.js:7:242)
    at Q.<anonymous> (/builds/assessfirst/frontend/af-library/node_modules/.pnpm/webfontloader@1.6.28/node_modules/webfontloader/webfontloader.js:7:370)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

Any updates or solutions ? 

Thanks !

**Comment by throrin19** [comment]
Same problem here, In our case it's only when we activate the webfontloader. 

Without it, it works fine but we have the default system policies :(

**Comment by zweeen** [comment]
Hi all :)

@Akryum  @hugoattal  any update on this issue ?
It's seems that it's coming from how Histoire is mocking `useNuxtApp` as  pointed out by @mvrlin https://github.com/mvrlin/nuxt-viewport/issues/44

**Comment by hugoattal** [comment]
@zweeen Sorry for this, could you (or anyone in this thread) please provide a [minimal reproductible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by d-low** [comment]
If you can isolate this issue to a single third party module, in my case [@fancyapps/ui](https://www.npmjs.com/package/@fancyapps/ui) was causing runtime errors in Histoire because `window` was undefined and these errors sometimes prevented Histoire from running; _and_ you are importing this third party module using a Nuxt plugin, then you can choose to disable the plugin when run in Historie using a workaround similar to the following:

1. Set an environment variable when running history in package.json:

   ```Json
   "scripts": {
      "story:dev": "IS_HISTOIRE=1 histoire dev"
   },
   ```

2. Expose this environment variable in your runtime config in nuxt.config.js:
   ```JavaScript
   runtimeConfig: {
     public: {
       isHistoire: process.env.IS_HISTOIRE,
     },
   },
   ```

3. Finally, don't import the offending module in your plug-in when run in Histoire:

   ```JavaScript
   export default defineNuxtPlugin(async () => {
     const config = useRuntimeConfig();

     if (config.public.isHistoire) {
       console.log('Fancyapps: Not loaded in Histoire!');
       return;
     }

     const { Fancybox } = await import('@fancyapps/ui');
     window.Fancybox = Fancybox;
   });
   ```
