### ISSUE TITLE
Histoire fails with Nuxt 3.3.3, requires @vitejs/plugin-vue to handle .vue files

### ISSUE THREAD

**Issue by smares** [histoire-dev/histoire#508]
### Describe the bug

Updating from Nuxt 3.3.2 to 3.3.3 gives me the following error now:

`Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.`

### Reproduction

Issue is obvious after upgrading from Nuxt 3.3.2 to Nuxt 3.3.3.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700T
    Memory: 27.45 GB / 31.19 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/bin/node
    Yarn: 3.5.0 - /usr/bin/yarn
    npm: 9.5.0 - /usr/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
  npmPackages:
    @histoire/plugin-nuxt: ^0.15.9 => 0.15.9 
    @histoire/plugin-vue: ^0.15.8 => 0.15.8 
    histoire: ^0.15.9 => 0.15.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by afif-hh** [comment]
are you using i18n plugin ?

**Comment by smares** [comment]
Nope

**Comment by Camoukey** [comment]
I also observe the problem on version nuxt 3.3.3

**Comment by danlourenco** [comment]
Same issue, post Nuxt 3.3.3 install.

**Comment by kylemilloy** [comment]
Same on 3.3.3

**Comment by danielroe** [comment]
@Akryum This is likely an issue with upgrade to Vite 4.2 under the hood. You may need to set `enforce: 'post'` if you need to ensure that the Vite Vue plugin has already run.

**Comment by rdhainaut** [comment]
> @Akryum This is likely an issue with upgrade to Vite 4.2 under the hood. You may need to set `enforce: 'post'` if you need to ensure that the Vite Vue plugin has already run.

@danielroe  Please can you tell in which file / section do you set that setting ? Thank you

**Comment by Akryum** [comment]
Could you try with Histoire 0.16?

**Comment by kylemilloy** [comment]
If you push it to npm we can :)

**Comment by kaesetoast** [comment]
Same error for me with 0.16:

```bash
12:12:01 [vite] warning: LintOnStart is turned on, and it will check for all matching files.
  Plugin: vite-plugin-eslint (x3)
Using 8 threads for story collection
Collect stories start all
  ➜  Local:   http://127.0.0.1:6006/
  ➜  Network: use --host to expose
Error while collecting story /home/philipp/Projects/unity-design-system/components/Backdrop/BackdropDefault.story.vue:
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
    at formatError (file:///home/philipp/Projects/unity-design-system/node_modules/vite/dist/node/chunks/dep-79892de8.js:43113:46)
    at TransformContext.error (file:///home/philipp/Projects/unity-design-system/node_modules/vite/dist/node/chunks/dep-79892de8.js:43109:19)
    at TransformContext.transform (file:///home/philipp/Projects/unity-design-system/node_modules/vite/dist/node/chunks/dep-79892de8.js:41313:22)
    at async Object.transform (file:///home/philipp/Projects/unity-design-system/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:30)
    at async loadAndTransform (file:///home/philipp/Projects/unity-design-system/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29)
Collect stories end 593ms
^C
➤  unity-design-system main ✗:$
```

**Comment by ctp-placebo** [comment]
I'm having the same problem with a project scaffolded with npm create vite@latest using Svelte as the template. 
No Nuxt, no Vue, nothing unusual.  
The template includes a component for a button to +1, Counter.svelte, very simple so no errors, and Histoire cannot find it.  
The story file is simple, looks like this: 
```
<svelte:options tag="cobalt-counter-hst" />
<script>
    import Counter from './Counter.svelte';
    export let Hst;
  </script>
  
  <Hst.Story title="Counter">
    <Counter />
  </Hst.Story>
```

Histoire itself opens on localhost with the sidebar etc, just can't collect any stories?  

Ubuntu 22.10 LTS
  npm: '9.6.2',
  node: '18.16.0',

**Comment by espy** [comment]
I have the same problem as the poster above, installing Histoire on an existing svelte/vite project and pointing it to a new `Meow.story.svelte` file with [the TS example code from the docs](https://histoire.dev/guide/svelte3/stories.html#typescript) leads to:

```
Error while collecting story 
/blah/src/components/Meow.story.svelte:
Error: Failed to parse source for import analysis because the content contains invalid JS syntax.
If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
```

**Comment by halimb** [comment]
Same issue here with `@histoire/plugin-vue2` on a fresh vue2 project.

`Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.`

**Comment by hinogi** [comment]
I also have that issue with just a template in the story file, while having vite and the plugin installed actually

**Comment by usrrname** [comment]
I too am having this issue on `nuxt@^3.6.5` and `nuxt@3.8.2` with vue 3.3.9

on `histoire dev` I get the following error despite importing `@vitejs/plugin-vue` in my `vite.config.ts`:

```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
    at formatError (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.13/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44062:46)
    at TransformContext.error (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.13/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
    at TransformContext.transform (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.13/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41784:22)
    at async Object.transform (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.13/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:30)
    at async loadAndTransform (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.13/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)
    at async ViteNodeServer._transformRequest (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite-node@0.34.6_@types+node@18.18.13/node_modules/vite-node/dist/server.mjs:358:16)
    at async ViteNodeServer._fetchModule (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/vite-node@0.34.6_@types+node@18.18.13/node_modules/vite-node/dist/server.mjs:329:17)
    at async MessagePort.<anonymous> (file:///Users/jenc/rivalry-nuxt3/node_modules/.pnpm/birpc@0.1.1/node_modules/birpc/dist/index.mjs:16:18)
```

I'm using the code from demos but it seems to think `Button.story.vue` should have a .tsx/.jsx extension 🤯
