### ISSUE TITLE
Nuxt 3.8.1 breaks Histoire Nuxt plugin

### ISSUE THREAD

**Issue by happy-turtle** [histoire-dev/histoire#630]
### Describe the bug

Updating to Nuxt 3.8.1 lets `histoire build` fail with the following error:
```
/home/projects/github-b638l4/node_modules/@histoire/plugin-nuxt/dist/index.js:135
    appPreset.imports = appPreset.imports.filter((i) => typeof i !== 'string' || !stubbedComposables.includes(i));

TypeError: Cannot read properties of undefined (reading 'imports')
    at eval (file:///home/projects/github-b638l4/node_modules/@histoire/plugin-nuxt/dist/index.js:135:35)
    at eval (file:///home/projects/github-b638l4/node_modules/hookable/dist/index.cjs:50:66)
    at Object.run (file:///home/projects/github-b638l4/node_modules/hookable/dist/index.cjs:43:43)
    at eval (file:///home/projects/github-b638l4/node_modules/hookable/dist/index.cjs:50:56)
    at async setup (file:///home/projects/github-b638l4/node_modules/nuxt/dist/index.mjs:2241:5)
    at async normalizedModule (file:///home/projects/github-b638l4/node_modules/@nuxt/kit/dist/index.mjs:2141:18)
    at async installModule (file:///home/projects/github-b638l4/node_modules/@nuxt/kit/dist/index.mjs:2439:95)
    at async initNuxt (file:///home/projects/github-b638l4/node_modules/nuxt/dist/index.mjs:3694:7)
```
Maybe this is caused by https://github.com/nuxt/nuxt/pull/23951?

### Reproduction

https://stackblitz.com/edit/github-b638l4

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
  npmPackages:
    @histoire/plugin-nuxt: ^0.17.4 => 0.17.4 
    @histoire/plugin-vue: ^0.17.4 => 0.17.4 
    histoire: ^0.17.4 => 0.17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by medfreeman** [comment]
This is covered by #627 :)

**Comment by zweeen** [comment]
> This is covered by #627 :)

This PR resolve the error, thx @danielroe 🙂

**Comment by happy-turtle** [comment]
Yes, I tried this morning and it's fixed 👍 Thanks!
