### ISSUE TITLE
Can't resolve dependencies correctly

### ISSUE THREAD

**Issue by kainstar** [histoire-dev/histoire#738]
### Describe the bug

When i import `lucide-vue-next`, histoire report it cannot find module:

```
Error while collecting story /Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/demo.story.vue:
Error: Cannot find module /Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/lucide-vue-next@0.397.0_vue@3.4.30/node_modules/lucide-vue-next/dist/esm imported from file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old, file:///Users/zsk/code/github.com/kainstar/reproduce/, file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/_index.js, file:///Users/zsk/code/github.com/kainstar/reproduce/node_modules
    at _resolve (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2102:19)
    at resolveSync (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2111:10)
    at resolvePathSync (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2121:24)
    at resolvePath (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2125:28)
    at isValidNodeImport (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2585:30)
    at _shouldExternalize (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:78:32)
    at shouldExternalize (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:55:19)
    at ViteNodeServer.shouldExternalize (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:225:12)
    at ViteNodeServer._fetchModule (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:322:36)
    at ViteNodeServer.fetchModule (file:///Users/zsk/code/github.com/kainstar/reproduce/histoire-vite-node-too-old/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:261:14)
```

### Reason and solution

After debug, i found it's because histoire using vite-node with a old version 0.34.7 whose latest version is 1.6.0, when i force using vite-node@1.6.0 with pnpm's overrides config, it works.

So is histoire has any play to upgrade vite-node to latest version?

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-hzthpp?file=src%2Fdemo.story.vue

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 772.61 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/18515_1719402069456/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/18515_1719402069456/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/18515_1719402069456/bin/npm
    pnpm: 8.15.1 - ~/Library/Caches/fnm_multishells/18515_1719402069456/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.126
    Safari: 17.4.1
  npmPackages:
    @histoire/plugin-vue: ^0.17.17 => 0.17.17 
    @vitejs/plugin-vue: ^5.0.5 => 5.0.5 
    histoire: ^0.17.17 => 0.17.17 
    vite: ^5.3.1 => 5.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by renatomoor** [comment]
I'm having the same issue when using the carousel component from shadcn-vue.

```Error while collecting story /Users/renatomoor/seelo/co-living-davos/resources/js/Components/ui/information-carousel/InformationCarousel.story.vue:
Error: Cannot find module /Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/embla-carousel-vue@8.1.7_vue@3.4.33/node_modules/embla-carousel-vue/esm imported from file:///Users/renatomoor/seelo/co-living-davos, file:///Users/renatomoor/seelo/, file:///Users/renatomoor/seelo/co-living-davos/_index.js, file:///Users/renatomoor/seelo/node_modules
    at _resolve (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2102:19)
    at resolveSync (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2111:10)
    at resolvePathSync (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2121:24)
    at resolvePath (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2125:28)
    at isValidNodeImport (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/mlly@1.7.1/node_modules/mlly/dist/index.mjs:2585:30)
    at _shouldExternalize (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:78:32)
    at shouldExternalize (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:55:19)
    at ViteNodeServer.shouldExternalize (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:225:12)
    at ViteNodeServer._fetchModule (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:322:36)
    at ViteNodeServer.fetchModule (file:///Users/renatomoor/seelo/co-living-davos/node_modules/.pnpm/vite-node@0.34.7/node_modules/vite-node/dist/server.mjs:261:14)
```

**Comment by renatomoor** [comment]
I've overrided to vite-node@2.0.3 but now I have this error in the console:

```Error while collecting story /Users/renatomoor/seelo/co-living-davos/node_modules/.histoire/plugins/builtin_tailwind-tokens/Tailwind.story.js:
/Users/renatomoor/seelo/co-living-davos/node_modules/.histoire/plugins/builtin_tailwind-tokens/Tailwind.story.js:1
import 'histoire-style'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by ColinEspinas** [comment]
We encountered the same issue:
```
Error while collecting story /home/cespinas/dev/netatmo/onesite/packages/ui/histoire/Banners.story.vue:
Error: Cannot find module /home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/lucide-vue-next@0.453.0_vue@3.5.12_typescript@5.5.4_/node_modules/lucide-vue-next/dist/esm imported from file:///home/cespinas/dev/netatmo/onesite/packages/ui, file:///home/cespinas/dev/netatmo/onesite/packages/, file:///home/cespinas/dev/netatmo/onesite/packages/ui/_index.js, file:///home/cespinas/dev/netatmo/onesite/packages/node_modules
    at _resolve (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/mlly@1.7.2/node_modules/mlly/dist/index.mjs:2102:19)
    at resolveSync (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/mlly@1.7.2/node_modules/mlly/dist/index.mjs:2111:10)
    at resolvePathSync (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/mlly@1.7.2/node_modules/mlly/dist/index.mjs:2121:24)
    at resolvePath (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/mlly@1.7.2/node_modules/mlly/dist/index.mjs:2125:28)
    at isValidNodeImport (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/mlly@1.7.2/node_modules/mlly/dist/index.mjs:2585:30)
    at _shouldExternalize (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/vite-node@0.34.7_@types+node@22.7.8_terser@5.31.6/node_modules/vite-node/dist/server.mjs:78:32)
    at shouldExternalize (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/vite-node@0.34.7_@types+node@22.7.8_terser@5.31.6/node_modules/vite-node/dist/server.mjs:55:19)
    at ViteNodeServer.shouldExternalize (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/vite-node@0.34.7_@types+node@22.7.8_terser@5.31.6/node_modules/vite-node/dist/server.mjs:225:12)
    at ViteNodeServer._fetchModule (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/vite-node@0.34.7_@types+node@22.7.8_terser@5.31.6/node_modules/vite-node/dist/server.mjs:322:36)
    at ViteNodeServer.fetchModule (file:///home/cespinas/dev/netatmo/onesite/node_modules/.pnpm/vite-node@0.34.7_@types+node@22.7.8_terser@5.31.6/node_modules/vite-node/dist/server.mjs:261:14)
```

Have a great day, Colin.

**Comment by maroluke** [comment]
When will that fix be released?

**Comment by UchVuch** [comment]
We faced the same problem when installing and importing embla-carousel-vue for our historie:
![image](https://github.com/user-attachments/assets/a3af4030-d6dd-4736-acc4-8ab50d4e4cbf)
![image](https://github.com/user-attachments/assets/67c465aa-72a0-43c4-9af6-e4dafe58019a)
![image](https://github.com/user-attachments/assets/9945bad2-de3c-4928-a543-adab8b00f2e8)
![image](https://github.com/user-attachments/assets/adf32f51-1aa3-4f55-8a23-cda89e5797f8)
![image](https://github.com/user-attachments/assets/cdf745bd-3ed9-47ef-8c99-869dfe456f57)


When started `npm run story:dev`:
![image](https://github.com/user-attachments/assets/4e43c196-4b00-4a09-9c8e-b2a12fe2dfa2)

**Comment by blu14x** [comment]
I am facing the same with simplex-noise


```
Error while collecting story /Users/blu/smf_projects/phoenix/frontend/components/molecules/app/HexGrid.story.vue:
Error: Cannot find module /Users/blu/smf_projects/phoenix/frontend/node_modules/simplex-noise/dist/esm imported from file:///Users/blu/smf_projects/phoenix/frontend, file:///Users/blu/smf_projects/phoenix/, file:///Users/blu/smf_projects/phoenix/frontend/_index.js, file:///Users/blu/smf_projects/phoenix/node_modules
    at _resolve (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/mlly/dist/index.mjs:2102:19)
    at resolveSync (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/mlly/dist/index.mjs:2111:10)
    at resolvePathSync (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/mlly/dist/index.mjs:2121:24)
    at resolvePath (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/mlly/dist/index.mjs:2125:28)
    at isValidNodeImport (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/mlly/dist/index.mjs:2585:30)
    at _shouldExternalize (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/histoire/node_modules/vite-node/dist/server.mjs:78:32)
    at shouldExternalize (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/histoire/node_modules/vite-node/dist/server.mjs:55:19)
    at ViteNodeServer.shouldExternalize (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/histoire/node_modules/vite-node/dist/server.mjs:225:12)
    at ViteNodeServer._fetchModule (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/histoire/node_modules/vite-node/dist/server.mjs:322:36)
    at ViteNodeServer.fetchModule (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/histoire/node_modules/vite-node/dist/server.mjs:261:14)
    at Proxy.fetchModule (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/histoire/dist/node/collect/index.js:50:37)
    at MessagePort.onMessage (file:///Users/blu/smf_projects/phoenix/frontend/node_modules/birpc/dist/index.mjs:91:29)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:825:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17)
```
